sudo: required
services:
    - docker

before_install:
   - docker build -t r/django -f Dockerfile.dev .
script:
   - docker run  r/django python ./motherfood/manage.py test    
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-Django"
  env: "DockerDjango-env" 
  bucket_name: "elasticbeanstalk-us-east-2-149157452571"
  bucket_path: "Docker-Django"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
