sudo: required
services:
    - docker

before_install:
   - docker build -t rkudache31/djangoweb:v1 .
script:
   - docker run  rkudache31/djangoweb:v1 python ./homefood/manage.py test    
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Myapp1"
  env: "Myapp1-env"
  bucket_name: "elasticbeanstalk-us-east-1-562256704977"
  bucket_path: "MyApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
