# Generated by Django 3.0.3 on 2020-05-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_desc',
            field=models.CharField(max_length=300),
        ),
    ]
